FROM golang:1.23-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev

# Set Go environment variables
ENV GO111MODULE=on
ENV CGO_ENABLED=0

# Copy go mod and sum files first
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Install goose for database migrations
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# Copy source code
COPY . .

# Command to run the application with hot reloading
CMD ["goose", "up"]
